dataset_csv: dataset_10k_elast/test/dataset.csv
results_folder: inferences_elast/GNN/
model_weights_path: elast_results_200e_bs16/no_div_no_periodic/weights/last_epoch_model_weights.pth
device: cuda # cpu
latent_size: 128
message_passing_steps: 10
batch_size: 32
periodic_graph: True
